services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  order-producer:
    build:
      context: ./backend
      dockerfile: Dockerfile.producer
    container_name: order-producer
    environment:
      RabbitMq__Host: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-net

  order-consumer:
    build:
      context: ./backend
      dockerfile: Dockerfile.consumer
    container_name: order-consumer
    environment:
      RabbitMq__Host: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend/order-app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - order-producer
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
