FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
WORKDIR /src
COPY Shared/ Shared/
COPY OrderConsumer/ OrderConsumer/
RUN dotnet publish OrderConsumer/OrderConsumer.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:10.0-alpine AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "OrderConsumer.dll"]
